export const data = JSON.parse("{\"key\":\"v-a898f99a\",\"path\":\"/blogs/OperationMaintenance/DockerCompose.html\",\"title\":\"Docker进阶之DockerCompose\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Docker进阶之DockerCompose\",\"tags\":[\"Docker\",\"Dockerfile\"],\"categories\":[\"OperationMaintenance\"],\"date\":\"2021-08-05T00:00:00.000Z\"},\"headers\":[{\"level\":2,\"title\":\"概要\",\"slug\":\"概要\",\"link\":\"#概要\",\"children\":[]},{\"level\":2,\"title\":\"安装\",\"slug\":\"安装\",\"link\":\"#安装\",\"children\":[]},{\"level\":2,\"title\":\"基本结构\",\"slug\":\"基本结构\",\"link\":\"#基本结构\",\"children\":[]},{\"level\":2,\"title\":\"常用指令\",\"slug\":\"常用指令\",\"link\":\"#常用指令\",\"children\":[]},{\"level\":2,\"title\":\"docker-compose.yaml语法\",\"slug\":\"docker-compose-yaml语法\",\"link\":\"#docker-compose-yaml语法\",\"children\":[{\"level\":3,\"title\":\"version：\",\"slug\":\"version\",\"link\":\"#version\",\"children\":[]},{\"level\":3,\"title\":\"services：\",\"slug\":\"services\",\"link\":\"#services\",\"children\":[]},{\"level\":3,\"title\":\"build：\",\"slug\":\"build\",\"link\":\"#build\",\"children\":[]},{\"level\":3,\"title\":\"command：\",\"slug\":\"command\",\"link\":\"#command\",\"children\":[]},{\"level\":3,\"title\":\"image：\",\"slug\":\"image\",\"link\":\"#image\",\"children\":[]},{\"level\":3,\"title\":\"expose\",\"slug\":\"expose\",\"link\":\"#expose\",\"children\":[]},{\"level\":3,\"title\":\"ports：\",\"slug\":\"ports\",\"link\":\"#ports\",\"children\":[]},{\"level\":3,\"title\":\"environment：\",\"slug\":\"environment\",\"link\":\"#environment\",\"children\":[]},{\"level\":3,\"title\":\"depends_on\",\"slug\":\"depends-on\",\"link\":\"#depends-on\",\"children\":[]},{\"level\":3,\"title\":\"networks：\",\"slug\":\"networks\",\"link\":\"#networks\",\"children\":[]},{\"level\":3,\"title\":\"links：\",\"slug\":\"links\",\"link\":\"#links\",\"children\":[]},{\"level\":3,\"title\":\"external_links：\",\"slug\":\"external-links\",\"link\":\"#external-links\",\"children\":[]},{\"level\":3,\"title\":\"volumes\",\"slug\":\"volumes\",\"link\":\"#volumes\",\"children\":[]},{\"level\":3,\"title\":\"env_file：\",\"slug\":\"env-file\",\"link\":\"#env-file\",\"children\":[]},{\"level\":3,\"title\":\"volumes_from\",\"slug\":\"volumes-from\",\"link\":\"#volumes-from\",\"children\":[]},{\"level\":3,\"title\":\"dns_search\",\"slug\":\"dns-search\",\"link\":\"#dns-search\",\"children\":[]},{\"level\":3,\"title\":\"extends\",\"slug\":\"extends\",\"link\":\"#extends\",\"children\":[]}]},{\"level\":2,\"title\":\"其他\",\"slug\":\"其他\",\"link\":\"#其他\",\"children\":[]}]}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
