name: blog deploy

on: 
  push:
    branches: 
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Debug KUBE_CONFIG_DATA
      run: |
        echo "KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}"
