name: blog deploy

on: 
  push:
    branches: 
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'

    - name: yarn install and build
      run: |
        node -v
        yarn install
        yarn build

    # 推送到 CleanCloud 云函数平台
    - name: Deploy to LeanEngine
      uses: enflo/curl-action@v1.2
      with:
        curl: -X POST https://us-w1-console-api.leancloud.app/1.1/engine/groups/web/production/version?gitTag=myblog&token=${{ secrets.DEPLOY_LEANCLOUD_TOKEN }}

    # 推送 docker 镜像到阿里云私有仓库
    - uses: aliyun/acr-login@v1                                               # 使用阿里云镜像服务action
      env:
        docker_repo: registry.cn-hangzhou.aliyuncs.com/aliyun-docker-rep      # 指定自己的仓库地址
        image_name: blog                                                      # 指定镜像名称
        tag: ${{ github.sha }}                                                # 指定镜像标签
    - run: |
        docker version
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com     # 登录阿里云镜像仓库
        docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/aliyun-docker-rep/blog:${{ github.sha }}                      # 使用Dockerfile构建镜像
        docker push registry.cn-hangzhou.aliyuncs.com/aliyun-docker-rep/blog:${{ github.sha }}                                                 # 推送镜像到镜像仓库

    # 配置kubectl环境并更新pod
    - name: setup Kubeconfig and apply this deployment.yaml
      run: |
        sed -i 's/{TAG}/${{ github.sha }}/g' deployment.yaml                  # 将sha值作为更新deploy镜像版本号更新yaml
        echo "${{ secrets.KUBECONFIG_CONTENTS }}" > kubeconfig.yaml           # 配置kubectl环境           
        kubectl --kubeconfig=kubeconfig.yaml apply -f deployment.yaml         # 更新pod
      env:
        KUBECONFIG: kubeconfig.yaml
    
    # 推送 github action 执行成功到iphone
    - name: push github action to iphone
      run: curl --location --request POST 'https://api2.pushdeer.com/message/push?pushkey=${{ secrets.PUSHDEER_KEY }}&text='github_action_execute_successfully''
