export const data = JSON.parse("{\"key\":\"v-77881b31\",\"path\":\"/blogs/SpringCloudNotes/01SpringCloud.html\",\"title\":\"SpringCloud\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"SpringCloud\",\"tags\":[\"SpringCloud\"],\"categories\":[\"SpringCloudNotes\"],\"date\":\"2021-02-08T00:00:00.000Z\"},\"headers\":[{\"level\":2,\"title\":\"什么是SpringCloud\",\"slug\":\"什么是springcloud\",\"link\":\"#什么是springcloud\",\"children\":[{\"level\":3,\"title\":\"目标\",\"slug\":\"目标\",\"link\":\"#目标\",\"children\":[]},{\"level\":3,\"title\":\"简介\",\"slug\":\"简介\",\"link\":\"#简介\",\"children\":[]}]},{\"level\":2,\"title\":\"整体架构\",\"slug\":\"整体架构\",\"link\":\"#整体架构\",\"children\":[]},{\"level\":2,\"title\":\"SpringCloud的版本关系\",\"slug\":\"springcloud的版本关系\",\"link\":\"#springcloud的版本关系\",\"children\":[{\"level\":3,\"title\":\"SpringCloud和SpringBoot版本对应关系\",\"slug\":\"springcloud和springboot版本对应关系\",\"link\":\"#springcloud和springboot版本对应关系\",\"children\":[]},{\"level\":3,\"title\":\"SpringCloud和各子项目版本对应关系\",\"slug\":\"springcloud和各子项目版本对应关系\",\"link\":\"#springcloud和各子项目版本对应关系\",\"children\":[]}]},{\"level\":2,\"title\":\"SpringCloud子项目简介\",\"slug\":\"springcloud子项目简介\",\"link\":\"#springcloud子项目简介\",\"children\":[{\"level\":3,\"title\":\"Spring Cloud Netflix\",\"slug\":\"spring-cloud-netflix\",\"link\":\"#spring-cloud-netflix\",\"children\":[]},{\"level\":3,\"title\":\"Spring Cloud OpenFeign\",\"slug\":\"spring-cloud-openfeign\",\"link\":\"#spring-cloud-openfeign\",\"children\":[]},{\"level\":3,\"title\":\"Spring Cloud Config\",\"slug\":\"spring-cloud-config\",\"link\":\"#spring-cloud-config\",\"children\":[]},{\"level\":3,\"title\":\"Spring Cloud Bus\",\"slug\":\"spring-cloud-bus\",\"link\":\"#spring-cloud-bus\",\"children\":[]},{\"level\":3,\"title\":\"Spring Cloud Sleuth\",\"slug\":\"spring-cloud-sleuth\",\"link\":\"#spring-cloud-sleuth\",\"children\":[]},{\"level\":3,\"title\":\"Spring Cloud Consul\",\"slug\":\"spring-cloud-consul\",\"link\":\"#spring-cloud-consul\",\"children\":[]},{\"level\":3,\"title\":\"Spring Cloud Gateway\",\"slug\":\"spring-cloud-gateway\",\"link\":\"#spring-cloud-gateway\",\"children\":[]},{\"level\":3,\"title\":\"Spring Cloud Admin\",\"slug\":\"spring-cloud-admin\",\"link\":\"#spring-cloud-admin\",\"children\":[]},{\"level\":3,\"title\":\"Spring Cloud Security\",\"slug\":\"spring-cloud-security\",\"link\":\"#spring-cloud-security\",\"children\":[]},{\"level\":3,\"title\":\"Spring Cloud Alibaba\",\"slug\":\"spring-cloud-alibaba\",\"link\":\"#spring-cloud-alibaba\",\"children\":[]},{\"level\":3,\"title\":\"Spring Cloud Stream\",\"slug\":\"spring-cloud-stream\",\"link\":\"#spring-cloud-stream\",\"children\":[]},{\"level\":3,\"title\":\"Spring Cloud Task\",\"slug\":\"spring-cloud-task\",\"link\":\"#spring-cloud-task\",\"children\":[]},{\"level\":3,\"title\":\"Spring Cloud Zookeeper\",\"slug\":\"spring-cloud-zookeeper\",\"link\":\"#spring-cloud-zookeeper\",\"children\":[]}]}]}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
